;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
		c-electric-colon
		c-electric-delete-forward
		c-electric-lt-gt
		c-electric-pound
		c-electric-semi&comma
		c-electric-slash
		c-electric-star
		c-indent-line-or-region
		c-toggle-electric-state
		complete-symbol
		downcase-region
		duplicate-thing
		eval-print-last-sexp
		helm-show-kill-ring
		hungry-delete-backward
		hungry-delete-forward
		kill-region
		move-text-up
		org-beginning-of-line
		org-end-of-line
		org-insert-todo-heading
		org-meta-return
		org-metaright
		org-self-insert-command
		org-set-tags-command
		org-shiftright
		smex
		sp--self-insert-command
		transpose-words
		upcase-region
		))

(setq mc/cmds-to-run-once
      '(
		handle-select-window
		helm-buffers-list
		switch-window
		))
