;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
        ace-jump-word-mode
        c-electric-brace
        c-electric-colon
        c-electric-delete-forward
        c-electric-lt-gt
        c-electric-paren
        c-electric-pound
        c-electric-semi&comma
        c-electric-slash
        c-electric-star
        c-indent-line-or-region
        c-toggle-electric-state
        comint-delchar-or-maybe-eof
        comment-dwim
        complete-symbol
        downcase-region
        duplicate-thing
        electric-newline-and-maybe-indent
        eval-print-last-sexp
        helm-maybe-exit-minibuffer
        helm-show-kill-ring
        hungry-delete-backward
        hungry-delete-forward
        indent-for-tab-command
        insert-register
        keyboard-quit
        kill-region
        move-text-down
        move-text-up
        org-beginning-of-line
        org-end-of-line
        org-insert-todo-heading
        org-kill-line
        org-meta-return
        org-metaright
        org-self-insert-command
        org-set-tags-command
        org-shiftleft
        org-shiftright
        sgml-slash
        smex
        sp--self-insert-command
        transpose-words
        upcase-region
        yaml-electric-backspace
        ))

(setq mc/cmds-to-run-once
      '(
        c-up-conditional
        diff-hl-next-hunk
        end-of-buffer
        handle-select-window
        helm-buffers-list
        switch-window
        ))
