#! /bin/bash

HAS_INSTANCE=`ls ~/.emacs.d/ | grep server.lock | wc -l`
HAS_LOCK=`ls ~/.emacs.d/ | grep daemon.lock | wc -l`

touch ~/.emacs.d/daemon.lock

if [[ "$HAS_INSTANCE" == "1" ]] ; then
	rm ~/.emacs.d/daemon.lock

	echo $@ | xargs emacsclient -c -n &
elif [[ "$HAS_LOCK" == "0" ]] ; then
	emacs --daemon

	rm ~/.emacs.d/daemon.lock

	echo $@ | xargs emacsclient -c -n &
else
	sleep 0.1s
	~/.emacs.d/run-emacs
fi
