#! /bin/bash

HAS_INSTANCE=`ls ~/.emacs.d/ | grep server.lock | wc -l`
HAS_LOCK=`ls ~/.emacs.d/ | grep daemon.lock | wc -l`

touch ~/.emacs.d/daemon.lock

function runClient() {
	if [ -z "$@" ] ; then
		emacsclient .
	else
		echo "$@" | xargs emacsclient
	fi
	rm ~/.emacs.d/daemon.lock
}

if [ "$HAS_INSTANCE" -eq "1" ] ; then
	runClient "$@"
elif [ "$HAS_LOCK" -eq "0" ] ; then
	emacs --daemon
	runClient "$@"
else
	sleep 0.2s
	echo "$@" | xargs ~/.emacs.d/run-emacs
fi
